version: "3"

services:
  mongo-db:
    image: mongo:latest
    ports:
      - '27017:27017'
    command:
      - --storageEngine=wiredTiger
    volumes:
      - mongo-db:/data/db
    logging:
      driver: none

volumes:
  mongo-db:
